name: safepo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - backcall=0.2.0
  - ca-certificates=2025.8.3
  - comm=0.2.2
  - debugpy=1.6.7
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libkrb5=1.21.3
  - libsodium=1.0.20
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - lmdb=0.9.31
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.5.2
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - python=3.8.20
  - python_abi=3.8
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.0
      - annotated-types==0.7.0
      - cachetools==5.5.2
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpickle==3.1.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==4.4.2
      - eval-type-backport==0.2.2
      - farama-notifications==0.0.4
      - filelock==3.13.1
      - fonttools==4.57.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.9.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - gymnasium==0.28.1
      - gymnasium-robotics==1.2.2
      - idna==3.10
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.5
      - jax-jumpy==1.0.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - moviepy==1.0.3
      - mpmath==1.3.0
      - mujoco==2.3.3
      - networkx==3.0
      - ninja==1.11.1.4
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - oauthlib==3.3.0
      - pandas==2.0.3
      - pettingzoo==1.24.3
      - pillow==10.2.0
      - proglog==0.1.12
      - protobuf==5.29.5
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygame==2.1.0
      - pygments==2.19.1
      - pyopengl==3.1.9
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rsa==4.9.1
      - safety-gymnasium==1.2.0
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - torch==2.4.1+cu118
      - torchaudio==2.4.1+cu118
      - torchvision==0.19.1+cu118
      - tqdm==4.67.1
      - triton==3.0.0
      - tzdata==2025.2
      - urllib3==2.2.3
      - wandb==0.20.1
      - werkzeug==3.0.6
      - xmltodict==0.14.2
      - zipp==3.20.2
